# Numpy

In [1]:
import numpy as np

## creat arrays

In [27]:
np.array([1,2,3,4,5]) #Numpy is constrained to arrays that all contain the same type

array([1, 2, 3, 4, 5])

In [28]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [31]:
np.array([range(i,i+3) for i in [2,5,8]])

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [32]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [33]:
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.full((3,5),0.99)

array([[0.99, 0.99, 0.99, 0.99, 0.99],
       [0.99, 0.99, 0.99, 0.99, 0.99],
       [0.99, 0.99, 0.99, 0.99, 0.99]])

In [35]:
np.arange(1,20,4)

array([ 1,  5,  9, 13, 17])

In [38]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [39]:
np.random.random((3,3)) #3X3, random values between 0 and 1

array([[0.21952245, 0.04650706, 0.06318413],
       [0.71301936, 0.29958933, 0.43814231],
       [0.98370623, 0.04547579, 0.3640243 ]])

In [43]:
np.random.normal(0,1,(3,3)) #3X3, mean=0, std=1

array([[-0.73980951, -0.90300798,  0.98968927],
       [ 0.79257338, -0.02559958,  1.53387867],
       [ 0.36325967, -0.59933699,  0.35145865]])

In [44]:
np.random.randint(0,10,(3,3)) #3X3, random int in [0,10)

array([[6, 7, 0],
       [9, 8, 2],
       [6, 3, 1]])

In [53]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [54]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(4) 

array([1., 1., 1., 1.])

## The basics of Numpy Arrays

In [56]:
np.random.seed(0)

In [131]:
x1=np.random.randint(10,size=6)
x2=np.random.randint(10,size=(3,4))
x3=np.random.randint(10,size=(3,4,5))

In [133]:
x1

array([7, 2, 3, 1, 9, 5])

In [134]:
x2

array([[9, 9, 2, 0],
       [9, 1, 9, 0],
       [6, 0, 4, 8]])

In [135]:
x3

array([[[4, 3, 3, 8, 8],
        [7, 0, 3, 8, 7],
        [7, 1, 8, 4, 7],
        [0, 4, 9, 0, 6]],

       [[4, 2, 4, 6, 3],
        [3, 7, 8, 5, 0],
        [8, 5, 4, 7, 4],
        [1, 3, 3, 9, 2]],

       [[5, 2, 3, 5, 7],
        [2, 7, 1, 6, 5],
        [0, 0, 3, 1, 9],
        [9, 6, 6, 7, 8]]])

In [64]:
print('x3 ndim: ',x3.ndim)
print('x3 shape: ', x3.shape)
print('x3 size: ', x3.size)
print('x3 type: ', x3.dtype)
print('x3 itemsize: ', x3.itemsize, 'bytes')
print('x3 nbytes: ', x3.nbytes, 'bytes')

x3 ndim:  3
x3 shape:  (3, 4, 5)
x3 size:  60
x3 type:  int32
x3 itemsize:  4 bytes
x3 nbytes:  240 bytes


In [65]:
x1

array([2, 7, 2, 9, 2, 3])

In [66]:
x1[0]

2

In [72]:
x1[0]=9.99 #it will be truncated
x1

array([9, 7, 2, 9, 2, 3])

In [68]:
x1[-1]

3

In [69]:
x2

array([[3, 2, 3, 4],
       [1, 2, 9, 1],
       [4, 6, 8, 2]])

In [70]:
x2[0,0]

3

In [81]:
x2[0,0]=19  #modify values
x2

array([[19,  2,  3,  4],
       [ 1,  2,  9,  1],
       [ 4,  6,  8,  2]])

In [74]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
x[:5]

array([0, 1, 2, 3, 4])

In [79]:
x[::2]

array([0, 2, 4, 6, 8])

In [80]:
x2[::-1,::-1]

array([[ 2,  8,  6,  4],
       [ 1,  9,  2,  1],
       [ 4,  3,  2, 19]])

In [83]:
x2_sub=x2[:2,:2]
x2_sub

array([[19,  2],
       [ 1,  2]])

In [84]:
x2_sub[0,0]=99
x2_sub

array([[99,  2],
       [ 1,  2]])

In [86]:
x2 
#array slices return views rather than copies
#which means the original array will change 

array([[99,  2,  3,  4],
       [ 1,  2,  9,  1],
       [ 4,  6,  8,  2]])

In [87]:
x2_sub_copy=x2[:2,:2].copy()

In [91]:
x2_sub_copy[0,0]=100
print(x2_sub_copy)
print('-----------------')
print(x2) #the original array won't change with .copy()

[[100   2]
 [  1   2]]
-----------------
[[99  2  3  4]
 [ 1  2  9  1]
 [ 4  6  8  2]]


### reshape

In [94]:
grid=np.arange(1,10).reshape((3,3))
grid

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### concatenation , vstack, hstack

In [100]:
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [101]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [102]:
a=np.array([11,22,33])
np.vstack([a,grid])

array([[11, 22, 33],
       [ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [106]:
b=np.array([[44],[55],[66]])
np.hstack([grid,b])

array([[ 1,  2,  3, 44],
       [ 4,  5,  6, 55],
       [ 7,  8,  9, 66]])

### split

In [110]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
y1,y2,y3=np.split(x,[3,5])
print(y1,y2,y3)

[0 1 2] [3 4] [5 6 7 8 9]


In [124]:
y1,y2,y3=np.split(x,[4,5])
print(y1,y2,y3)

[0 1 2 3] [4] [5 6 7 8 9]


In [125]:
grid=np.arange(16).reshape(4,4)
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [128]:
upper,lower=np.vsplit(grid,[3])
print(upper)
print('---------------')
print(lower)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------
[[12 13 14 15]]


In [129]:
left,right=np.hsplit(grid,[3])
print(left)
print('-------------')
print(right)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]
 [12 13 14]]
-------------
[[ 3]
 [ 7]
 [11]
 [15]]


In [ ]:
#np.dsplit will split arrays along the third axis

## Universal Functions

In [141]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [142]:
x+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
np.add(x,2)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [144]:
#  +,-,*,/,//,**,%

In [148]:
x=np.array([-2,-11,3,-8,9])
x

array([ -2, -11,   3,  -8,   9])

In [147]:
abs(x)

array([ 2, 11,  3,  8,  9])

In [149]:
np.abs(x)

array([ 2, 11,  3,  8,  9])

In [150]:
np.absolute(x)

array([ 2, 11,  3,  8,  9])

### Trigonometric functions

In [157]:
theta=np.linspace(0,np.pi,3)
theta

array([0.        , 1.57079633, 3.14159265])

In [158]:
print("theta      = ", theta)        
print("sin(theta) = ", np.sin(theta))        
print("cos(theta) = ", np.cos(theta))        
print("tan(theta) = ", np.tan(theta))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [156]:
x = [-1, 0, 1]       
print("x         = ", x)        
print("arcsin(x) = ", np.arcsin(x))        
print("arccos(x) = ", np.arccos(x))        
print("arctan(x) = ", np.arctan(x))

x         =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


### Exponents and logarithms

In [160]:
 x = [1, 2, 3]        
print("x     =", x)        
print("e^x   =", np.exp(x))        
print("2^x   =", np.exp2(x))        
print("3^x   =", np.power(3, x))

x     = [1, 2, 3]
e^x   = [ 2.71828183  7.3890561  20.08553692]
2^x   = [2. 4. 8.]
3^x   = [ 3  9 27]


In [161]:
x = [1, 2, 4, 10]        
print("x        =", x)        
print("ln(x)    =", np.log(x))        
print("log2(x)  =", np.log2(x))        
print("log10(x) =", np.log10(x))

x        = [1, 2, 4, 10]
ln(x)    = [0.         0.69314718 1.38629436 2.30258509]
log2(x)  = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [163]:
 from scipy import special

In [165]:
 #Gamma functions 
x = [1, 5, 10]        
print("gamma(x)     =", special.gamma(x))        
print("ln|gamma(x)| =", special.gammaln(x))        
print("beta(x, 2)   =", special.beta(x, 2))

gamma(x)     = [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| = [ 0.          3.17805383 12.80182748]
beta(x, 2)   = [0.5        0.03333333 0.00909091]


### Advanced ufunc features

In [180]:
x=np.arange(5)
y=np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [182]:
y=np.zeros(10)
np.power(2,x,out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [185]:
x=np.arange(1,6)
np.add.reduce(x)

15

In [186]:
np.multiply.reduce(x)

120

In [187]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15], dtype=int32)

In [188]:
np.multiply.accumulate(x)

array([  1,   2,   6,  24, 120], dtype=int32)

In [190]:
x=np.arange(1,6)
np.multiply.outer(x,x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])

### Aggregations: min,max

In [195]:
x=np.random.random(100)
%timeit sum(x)

43 µs ± 1.89 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [196]:
%timeit np.sum(x) #much faster

10.7 µs ± 698 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [197]:
np.min(x)

0.008511590056627494

In [199]:
np.max(x)

0.9911416509743957

In [6]:
M=np.random.random((3,4))
M

array([[0.36616934, 0.16349478, 0.35249572, 0.01705962],
       [0.85012997, 0.80757276, 0.44508108, 0.45003545],
       [0.00652969, 0.83329051, 0.25385444, 0.75548462]])

In [11]:
M.sum()

5.30119798094403

In [203]:
M.min(axis=0)

array([0.14587015, 0.33563098, 0.23804352, 0.36130568])

In [204]:
M.min(axis=1)

array([0.23804352, 0.14587015, 0.43415558])

In [12]:
#np.sum       np.nansum     Compute sum of elements 
#np.prod     np.nanprod     Compute product of elements 
#np.mean     np.nanmean      Compute median of elements 
#np.std      np.nanstd       Compute standard deviation 
#np.var      np.nanvar       Compute variance 
#np.min      np.nanmin        Find minimum value 
#np.max      p.nanmax         Find maximum value 
#np.argmin   np.nanargmin     Find index of minimum value 
#np.argmax   np.nanargmax      Find index of maximum value 
#np.median   np.nanmedian      Compute median of elements 
#np.percentile   np.nanpercentile      Compute rank-based statistics of elements 
#np.any   N/A     Evaluate whether any elements are true 
#np.all   N/A     Evaluate whether all elements are true

In [214]:
print('25th percentile: ', np.percentile(M,25))
print('Median: ', np.median(M))

25th percentile:  0.3548870059282578
Median:  0.5488595066494614


### Brodadcasting

In [19]:
a=np.array([1,2,3])
b=np.array([5,5,5])
a+b

array([6, 7, 8])

In [20]:
a+10

array([11, 12, 13])

In [22]:
M=np.ones((3,3))
M

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
a+M

array([[2., 3., 4.],
       [2., 3., 4.],
       [2., 3., 4.]])

In [27]:
a=np.arange(3)
b=np.arange(3)[:,np.newaxis]
print(a)
print('----------')
print(b)
print('-----------')
print(a+b)

[0 1 2]
----------
[[0]
 [1]
 [2]]
-----------
[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [35]:
x=np.random.random((5,3))
xmean=x.mean(0)
print(xmean)

[0.60436135 0.53952212 0.6628518 ]


In [36]:
xcentered=x-xmean
print(xcentered)

[[-0.14248181  0.05628353 -0.06346048]
 [ 0.1469957  -0.41232789 -0.52624185]
 [ 0.10826038  0.44160628  0.29279782]
 [-0.44217878 -0.28135506  0.00478175]
 [ 0.3294045   0.19579314  0.29212277]]


### Comparisons, Masks, Boolean Logic

In [3]:
x=np.array([1,2,3,4,5])
x<3

array([ True,  True, False, False, False])

In [43]:
# ==,  !=,  <,  >,  <=, >=

In [4]:
x=np.random.randint(10,size=(3,4))
x

array([[4, 5, 1, 8],
       [0, 8, 1, 0],
       [5, 6, 0, 8]])

In [5]:
x<6

array([[ True,  True,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True, False]])

In [6]:
x[x<6]

array([4, 5, 1, 0, 1, 0, 5, 0])

In [7]:
np.count_nonzero(x<6)

8

In [8]:
np.sum(x<6)  #less than6, false=0, true=1

8

In [9]:
np.sum(x<6,axis=1) #less than 6 in each row

array([3, 3, 2])

In [51]:
np.any(x>8)

True

In [13]:
np.all(x<8,axis=1)

array([False, False, False])

In [14]:
np.sum((x>5)&( x<8))

1

In [15]:
np.sum(~((x<=5)|(x>=8)))

1

In [17]:
x[(x>5)&( x<8)]

array([6])

In [69]:
# & np.bitwise_and 
# | np.bitwise_or 
# ^ np.bitwise_xor
# ~ np.bitwise_not

### Fancy Indexing

In [18]:
rand=np.random.RandomState(42)

In [20]:
x=rand.randint(100, size=10)
print(x)

[87 99 23  2 21 52  1 87 29 37]


In [26]:
ind=[2,4,6,8]
x[ind]

array([23, 21,  1, 29])

In [25]:
x[np.array([[2,4],[6,8]])]

array([[23, 21],
       [ 1, 29]])

In [27]:
x=np.arange(12).reshape(3,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
row=np.array([0,1,2])
col=np.array([0,1,2])
x[row,col]

array([ 0,  5, 10])

In [30]:
x[row[:,np.newaxis],col]

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10]])

In [31]:
x[2,[3,2,1]]

array([11, 10,  9])

In [32]:
x=np.arange(10)
i=np.array([1,3,5,7])
x[i]=999
print(x)

[  0 999   2 999   4 999   6 999   8   9]


In [33]:
x[i]-=100
print(x)

[  0 899   2 899   4 899   6 899   8   9]


In [35]:
x=np.zeros(10)
i=[2,3,3,4,4,4,5,5]
x[i]+=10
x

array([ 0.,  0., 10., 10., 10., 10.,  0.,  0.,  0.,  0.])

In [37]:
x=np.zeros(10)
np.add.at(x,i,10)
print(x)

[ 0.  0. 10. 20. 30. 20.  0.  0.  0.  0.]


### Sorting Arrays

In [38]:
np.sort(x)

array([ 0.,  0.,  0.,  0.,  0.,  0., 10., 20., 20., 30.])

In [40]:
x.sort()
print(x)

[ 0.  0.  0.  0.  0.  0. 10. 20. 20. 30.]


In [43]:
x=np.array([2,1,4,3,5])
i=np.argsort(x)  #return indices
print(i)

[1 0 3 2 4]


In [44]:
x[i]

array([1, 2, 3, 4, 5])

In [45]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [46]:
np.sort(x, axis=0) #sort each column of x

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [47]:
np.sort(x, axis=1) #sort each row of x

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

In [48]:
#Partial Sorts: Partitioning
x=np.array([7,2,1,3,6,5,4])
np.partition(x,3)   #first three values are the three smallest. arbitrary order.

array([2, 3, 1, 4, 6, 5, 7])

In [49]:
rand=np.random.RandomState(42)
x=rand.randint(0,10,(4,6))
print(x)

[[6 3 7 4 6 9]
 [2 6 7 4 3 7]
 [7 2 5 4 1 7]
 [5 1 4 0 9 5]]


In [51]:
np.partition(x,2, axis=1)

array([[3, 4, 6, 7, 6, 9],
       [2, 3, 4, 7, 6, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 9, 5]])